version: "3.9"

services:
  app:
    container_name: fastapi_app
    build: ./
    env_file:
      - backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    restart: always
  db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - backend/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: